import StudyCore
import SwiftUI
import UIKit

/// Colour tokens. The values live in `Assets.xcassets` (generated by `tools/make_assets.py`),
/// with a light and a dark variant for every token.
enum ThemeToken: String, CaseIterable {
    case bg = "Bg"
    case surface = "Surface"
    case surfaceMuted = "SurfaceMuted"
    case border = "Border"
    case textPrimary = "TextPrimary"
    case textSecondary = "TextSecondary"
    case accent = "Accent"
    case accentGradientTop = "AccentGradientTop"
    case badge = "Badge"
    case success = "Success"
    case warning = "Warning"
    case levelA1 = "LevelA1"
    case levelA2 = "LevelA2"
    case levelB1 = "LevelB1"
    case levelB2 = "LevelB2"
    case levelC1 = "LevelC1"

    var color: Color { Color(rawValue) }
    var uiColor: UIColor? { UIColor(named: rawValue) }
}

enum Theme {
    static let bg = ThemeToken.bg.color
    static let surface = ThemeToken.surface.color
    static let surfaceMuted = ThemeToken.surfaceMuted.color
    static let border = ThemeToken.border.color
    static let textPrimary = ThemeToken.textPrimary.color
    static let textSecondary = ThemeToken.textSecondary.color
    static let accent = ThemeToken.accent.color
    static let accentGradientTop = ThemeToken.accentGradientTop.color
    static let badge = ThemeToken.badge.color
    static let success = ThemeToken.success.color
    static let warning = ThemeToken.warning.color

    static func level(_ level: CEFRLevel) -> Color {
        switch level {
        case .a1: ThemeToken.levelA1.color
        case .a2: ThemeToken.levelA2.color
        case .b1: ThemeToken.levelB1.color
        case .b2: ThemeToken.levelB2.color
        case .c1: ThemeToken.levelC1.color
        }
    }

    enum Radius {
        static let card: CGFloat = 32
        static let chip: CGFloat = 22
    }

    enum Size {
        static let pillButtonHeight: CGFloat = 56
        static let chip: CGFloat = 44
    }

    enum Spacing {
        static let small: CGFloat = 8
        static let medium: CGFloat = 16
        static let large: CGFloat = 20
        static let screen: CGFloat = 24
    }

    /// Text styles scale with Dynamic Type.
    enum Typography {
        /// Screen and card titles: serif, bold.
        static let screenTitle = Font.system(.title, design: .serif, weight: .bold)
        static let cardTitle = Font.system(.title2, design: .serif, weight: .bold)
        static let body = Font.system(.body, design: .rounded)
        static let bodyEmphasized = Font.system(.body, design: .rounded, weight: .semibold)
        static let caption = Font.system(.subheadline, design: .rounded)
        static let small = Font.system(.footnote, design: .rounded)
        static let button = Font.system(.title3, design: .rounded, weight: .semibold)
        static let timer = Font.system(.largeTitle, design: .rounded, weight: .bold).monospacedDigit()
    }
}

extension View {
    /// The soft shadow under cards and primary buttons.
    func cardShadow() -> some View {
        shadow(color: .black.opacity(0.06), radius: 12, x: 0, y: 8)
    }
}
